stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
    params:
      - data_ingestion.test_size

  data_transformation:
    cmd: python src/data_transformation.py
    deps:
      - src/data_transformation.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed
    outs:
      - data/features
    params:
      - feature_engineering.max_features

  model_trainer:
    cmd: python src/model_trainer.py
    deps:
      - src/model_trainer.py
      - data/features
    outs:
      - data/models/model.pkl
    params:
      - model_trainer.n_estimators
      - model_trainer.learning_rate

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/models
    outs:
      - data/reports/metrics.json